# The ID of your GitHub App
# id: $APP_ID
# webhook_secret: $WEBHOOK_SECRET
# private_key: $PRIVATE_KEY

# Set to true if your GitHub App was installed on a GitHub Enterprise instance
enterprise: false

# Array of webhook event names that your GitHub App subscribes to
default_events:
    - issue_comment
    - issues
    - pull_request
    - pull_request_review

# The permissions your app needs
default_permissions:
    # Repository contents, commits, branches, downloads, releases, and merges
    contents: write # Required for merging PRs

    # Issues and related comments, assignees, labels, and milestones
    issues: write # Required for managing labels and comments

    # Pull requests and related comments, assignees, labels, milestones, and merges
    pull_requests: write # Required for managing PRs and reviews

    # Organization members and teams
    members: read # Required for checking org membership in welcome automation

    # Repository metadata
    metadata: read # Required for basic repo info

    # Checks on code
    checks: read # Required for checking status before merge

    # Repository administration
    administration: none

    # Blocking and unblocking users
    blocking: none

    # Deployments and deployment statuses
    deployments: none

    # Repository packages
    packages: none

    # Repository pages
    pages: none

    # Repository projects
    projects: none

    # Security alerts
    security_events: none

    # Repository starring
    starring: none

    # Repository statuses
    statuses: none

    # Team discussions
    team_discussions: none

    # Workflows, workflow runs, and workflow dispatch
    workflows: none

# The name of the GitHub App. Defaults to the name specified in package.json
name: Repo Command

# The homepage of your GitHub App
url: https://github.com/aayushchugh/repo-command

# A description of the GitHub App
description: A GitHub bot for automating repository management tasks through commands and automations.

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app
public: true
