name: Auto Add Pull request to project

on:
    pull_request:
        types:
            - labeled
            - opened

jobs:
    add-to-project:
        name: Add pull request to project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/add-to-project@main
              with:
                  project-url: https://github.com/users/aayushchugh/projects/3
                  github-token: ${{ secrets.GH_TOKEN }}
